//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballMidterm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FantasyFootballEntities : DbContext
    {
        public FantasyFootballEntities()
            : base("name=FantasyFootballEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<FantasyFootballTeam> FantasyFootballTeams { get; set; }
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<GamesByWeek> GamesByWeeks { get; set; }
    
        public virtual ObjectResult<usp_FantasyFootballTeams_GetPlayersByUserID_Real_Result> usp_FantasyFootballTeams_GetPlayersByUserID_Real(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_FantasyFootballTeams_GetPlayersByUserID_Real_Result>("usp_FantasyFootballTeams_GetPlayersByUserID_Real", userIDParameter);
        }
    
        public virtual ObjectResult<string> usp_FantasyFootballTeams_GetTeamNameByUserID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_FantasyFootballTeams_GetTeamNameByUserID", userIDParameter);
        }
    
        public virtual int usp_FantasyFootballTeams_SaveTeam(string teamName, string qB, string rB1, string rB2, string wR1, string wR2, string tE, Nullable<int> userID)
        {
            var teamNameParameter = teamName != null ?
                new ObjectParameter("TeamName", teamName) :
                new ObjectParameter("TeamName", typeof(string));
    
            var qBParameter = qB != null ?
                new ObjectParameter("QB", qB) :
                new ObjectParameter("QB", typeof(string));
    
            var rB1Parameter = rB1 != null ?
                new ObjectParameter("RB1", rB1) :
                new ObjectParameter("RB1", typeof(string));
    
            var rB2Parameter = rB2 != null ?
                new ObjectParameter("RB2", rB2) :
                new ObjectParameter("RB2", typeof(string));
    
            var wR1Parameter = wR1 != null ?
                new ObjectParameter("WR1", wR1) :
                new ObjectParameter("WR1", typeof(string));
    
            var wR2Parameter = wR2 != null ?
                new ObjectParameter("WR2", wR2) :
                new ObjectParameter("WR2", typeof(string));
    
            var tEParameter = tE != null ?
                new ObjectParameter("TE", tE) :
                new ObjectParameter("TE", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_FantasyFootballTeams_SaveTeam", teamNameParameter, qBParameter, rB1Parameter, rB2Parameter, wR1Parameter, wR2Parameter, tEParameter, userIDParameter);
        }
    
        public virtual ObjectResult<usp_Players_GetByPosition_Result> usp_Players_GetByPosition(string position)
        {
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Players_GetByPosition_Result>("usp_Players_GetByPosition", positionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_Players_GetScore(string playerName)
        {
            var playerNameParameter = playerName != null ?
                new ObjectParameter("PlayerName", playerName) :
                new ObjectParameter("PlayerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_Players_GetScore", playerNameParameter);
        }
    
        public virtual ObjectResult<usp_Players_ReturnAll_Result> usp_Players_ReturnAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Players_ReturnAll_Result>("usp_Players_ReturnAll");
        }
    
        public virtual ObjectResult<usp_Players_ReturnFiltered_Result> usp_Players_ReturnFiltered(string filterString)
        {
            var filterStringParameter = filterString != null ?
                new ObjectParameter("FilterString", filterString) :
                new ObjectParameter("FilterString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Players_ReturnFiltered_Result>("usp_Players_ReturnFiltered", filterStringParameter);
        }
    
        public virtual int usp_Players_UpdateFFScores(string playerName)
        {
            var playerNameParameter = playerName != null ?
                new ObjectParameter("PlayerName", playerName) :
                new ObjectParameter("PlayerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Players_UpdateFFScores", playerNameParameter);
        }
    
        public virtual ObjectResult<usp_Users_GetUserByUserID_Result> usp_Users_GetUserByUserID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Users_GetUserByUserID_Result>("usp_Users_GetUserByUserID", userIDParameter);
        }
    
        public virtual ObjectResult<usp_Users_Login_Result> usp_Users_Login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Users_Login_Result>("usp_Users_Login", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_Users_SaveNewUser(string username, string password, string email)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_Users_SaveNewUser", usernameParameter, passwordParameter, emailParameter);
        }
    
        public virtual ObjectResult<usp_GamesByWeek_GetFantasyTeamScoreByWeek_Result> usp_GamesByWeek_GetFantasyTeamScoreByWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GamesByWeek_GetFantasyTeamScoreByWeek_Result>("usp_GamesByWeek_GetFantasyTeamScoreByWeek");
        }
    }
}
