//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballMidterm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesByWeek
    {
        public string Tm { get; set; }
        public int Year { get; set; }
        public System.DateTime Date { get; set; }
        public string Opp { get; set; }
        public string Week { get; set; }
        public string G { get; set; }
        public string Day { get; set; }
        public string Result { get; set; }
    }
}
