//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballMidterm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public string Player1 { get; set; }
        public int Year { get; set; }
        public int Age { get; set; }
        public string Team { get; set; }
        public int GS { get; set; }
        public string Position { get; set; }
        public int PlayerID { get; set; }
        public Nullable<int> FFScore { get; set; }
    }
}
